logging:
  config: classpath:log4j2-prod.xml
bitvito:
#  mysql:
#    enable: true
#    username: umc
#    password: EFnL77PD8iKGCwEF
#    url: jdbc:mysql://127.0.0.1:3306/umc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  matching:
    system:
      alwaysSerial: true
      contractName: usdt #其他合约需要修改
    rocket:
      groupName: test
      namespace: 127.0.0.1:9876
      topic-prefix: future_matching_order_request
      topic-orderly-prefix: future_matching_
      batch-size: 100
    id-generator:
      machineId: 0
      data-center-id: 0
      zk-address: 127.0.0.1:2181
    pulsar:
      url: pulsar://127.0.0.1:16650
      topic: persistent://bitvito/public/matching_order_request_tenant_1
      prod-topic: persistent://terra/public/matching_order_sort_1_
      create-topic: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/umc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: umc
    password: EFnL77PD8iKGCwEF
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 5
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: umcPool
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 10000
    password: CB480F385A0F479B
#  redis:
#    cluster:
#      nodes:
#        - redis-main-cluster.6ykkst.clustercfg.apne1.cache.amazonaws.com:6379
#      max-redirects: 3
#    password:
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 50
#        max-active: 100
#        max-wait: 10000
#    timeout: 5000
nacos:
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: buildex@2024
  discovery:
    server-addr: 127.0.0.1:8848
