logging:
  config: classpath:log4j2-test.xml
bitvito:
  mysql:
    enable: true
    username: umc
    password: EFnL77PD8iKGCwEF
    url: jdbc:mysql://65.1.166.28:3306/umc?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  matching:
    system:
      alwaysSerial: true
      contractName: usdt #其他合约需要修改
    rocket:
      groupName: test
      namespace: 192.168.112.20:9876
      topic-prefix: future_matching_order_request
      topic-orderly-prefix: future_matching_
      batch-size: 100
    id-generator:
      machineId: 0
      data-center-id: 0
      zk-address: 127.0.0.1::2181
    pulsar:
      url: pulsar://65.1.166.28:16650
      topic: persistent://aex/public/matching_order_request_tenant_1
      prod-topic: persistent://aex/public/matching_order_sort_1_
      create-topic: false
  apisix:
    jwt:
      key: 1111111111
      secret: 222222222
worker-id:
  apply:
    address: 111111
online:
  time: 182812912819
  register: true
spring:
  application:
    name: sort
  redis:
    host: 127.0.0.1
    port: 55001
    database: 2
    timeout: 10000
    password: redispw
#    password: CB480F385A0F479B
#  redis:
#    cluster:
#      nodes:
#        - 172.30.96.24:7001
#        - 172.30.96.24:7002
#        - 172.30.96.24:7003
#        - 172.30.96.24:7004
#        - 172.30.96.24:7005
#        - 172.30.96.24:7000
#      max-redirects: 3
#    password:
    lettuce:
      pool:
        max-idle: 50
        min-idle: 50
        max-active: 100
        max-wait: 10000
#    timeout: 5000
nacos:
  config:
    server-addr: 65.1.166.28:8848
    username: nacos
    password: buildex@2024
